// Corporate-Owned Work Profile
IntuneDevices
| where OS contains "Android (corporate-owned work profile)"
| summarize dcount(DeviceId) by OSVersion
| render columnchart

// Fully Managed
IntuneDevices
| where OS contains "Android (fully managed)"
| summarize dcount(DeviceId) by OSVersion
| render columnchart

// ADedicated
IntuneDevices
| where OS contains "Android (dedicated)"
| summarize dcount(DeviceId) by OSVersion
| render columnchart

// Personally-owned Work Profile
IntuneDevices
| where OS contains "Android (personally-owned work profile)"
| summarize dcount(DeviceId) by OSVersion
| render columnchart

// Device Administrator
IntuneDevices
| where OS contains "Android (device administrator)"
| summarize dcount(DeviceId) by OSVersion
| render columnchart
